name = "tabelas"
main = "src/index.ts"
compatibility_date = "2025-12-18"

[vars]
LIBSQL_DB_URL = "libsql://tabelasprecos-tabelas-precos.aws-us-east-1.turso.io"
ALLOWED_ORIGINS = "https://equipegf2.github.io"
